description = "Modern portfolio theme for your Hugo site."
homepage = "https://antoniopantaleo.github.io"
tags = ["Hugo", "theme", "portfolio", "modern", "responsive"]
features = ["clean", "gallery", "minimal", "minimalist", "mobile", "personal", "responsive", "simple", "tailwind", "projects", "white"]
languageCode = "en-us"
baseurl = "https://antoniopantaleo.github.io"
title = "Antonio Pantaleo"

[params]
  name = "Antonio Pantaleo"
  description = "Make a description"
  author = "Antonio Pantaleo"
  authorEmail = "antonio_pantaleo@icloud.com"
  authorImage = "/profile.png"
  autoDarkMode = true
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Antonio"
  tagline = "iOS Developer"
  description = "git-addicted, focused on state of the art technologies. I develop applications, tools and libraries"
  contact = "https://github.com/antoniopantaleo"
  showWork = false
  showEmailCTA = false

# Projects
[[params.homepage.project]]
  title = "APDynamicGrid"
  logo = "APDynamicGrid.png"
  url = "https://github.com/antoniopantaleo/APDynamicGrid"

[[params.homepage.project]]
  title = "APUtils"
  logo = "APUtils.png"
  url = "https://github.com/antoniopantaleo/APUtils"


[[params.homepage.project]]
  title = "ShellKit"
  logo = "ShellKit.png"
  url = "https://github.com/antoniopantaleo/ShellKit"

# Work Experience

[[params.homepage.resume.work]]
  name = "Alten"
  url="https://www.alten.it"
  role = "iOS Developer"
  duration = "Jun 2021 - Jun 2022"

[[params.homepage.resume.work]]
  name = "Iriscube Reply"
  url="https://www.reply.com/iriscube-reply/en/"
  role = "iOS Developer"
  duration = "Jun 2022 - Now"

[params.homepage.resume]
  skills = ["Visual Design", "Product Development"]

[[params.homepage.resume.courses]]
  name = "Design Principles"
  provider = "UX Academy"
  duration = "Nov 2019 - Jan 2020"

[params.homepage.social]
  # twitter = "https://twitter.com/"
  linkedin = "https://www.linkedin.com/in/antonio-pantaleo/"
  github = "https://github.com/antoniopantaleo"
  # medium = "https://medium.com/"
  reddit = "https://www.reddit.com/user/anouonauei"
  # dribbble = "https://dribbble.com/"

[build]
  writeStats = false

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "catppuccin-frappe"

[services]
  [services.googleAnalytics]
    id = 'G-PD53JWPPKZ'