description = "Modern portfolio theme for your Hugo site."
homepage = "https://github.com/apvarun/showfolio"
tags = ["Hugo", "theme", "portfolio", "modern", "responsive"]
features = ["clean", "gallery", "minimal", "minimalist", "mobile", "personal", "responsive", "simple", "tailwind", "projects", "white"]
languageCode = "en-us"
baseurl = "https://example.com"
title = "Antonio Pantaleo"

[params]
  name = "Antonio Pantaleo"
  description = "Make a description"
  author = "Antonio Pantaleo"
  authorEmail = "antonio_pantaleo@icloud.com"
  authorImage = "/profile.png"
  autoDarkMode = true
  showEmailCTA = false
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Antonio"
  tagline = "iOS Developer"
  description = "git-addicted, focused on state of the art technologies. I develop applications, tools and libraries"
  contact = "https://github.com/antoniopantaleo"

# Projects

[[params.homepage.project]]
  title = "APDynamicGrid"
  logo = "AP.png"
  url = "https://github.com/antoniopantaleo/APDynamicGrid"

# Work Experience

[[params.homepage.resume.work]]
  name = "Alten"
  url="https://www.alten.it"
  role = "iOS Developer"
  duration = "Jun 2021 - Jun 2022"

[[params.homepage.resume.work]]
  name = "Iriscube Reply"
  url="https://www.reply.com/iriscube-reply/en/"
  role = "iOS Developer"
  duration = "Jun 2022 - Now"

[params.homepage.resume]
  skills = ["Visual Design", "Product Development"]

[[params.homepage.resume.courses]]
  name = "Design Principles"
  provider = "UX Academy"
  duration = "Nov 2019 - Jan 2020"

[params.homepage.social]
  # twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"

[build]
  writeStats = false

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "nord"
